version: '3.0'

services:
  web:
    build: .
    command: python /sib/daemons/web.py run
    volumes:
      - ./daemons:/sib/daemons
      - ./src:/sib/src
    ports:
      - '127.0.0.1:5000:5000'
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbit
  rabbit:
    image: rabbitmq
    env_file:
      - .env
    restart: always
  worker-email:
    build: .
    command: python /sib/daemons/worker_email.py run
    volumes:
      - ./daemons:/sib/daemons
      - ./src:/sib/src
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbit
  worker-http:
    build: .
    command: python /sib/daemons/worker_http.py run
    volumes:
      - ./daemons:/sib/daemons
      - ./src:/sib/src
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbit
